version: "3.8"

services:
  db:
    image: mysql:8.0.28-debian
    restart: always
    environment:
      MYSQL_DATABASE: 'public_transport_app' # So you don't have to use root, but you can if you like
      MYSQL_USER: 'daniel' # You can use whatever password you like
      MYSQL_PASSWORD: 'password' # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports: # <Port exposed> : < MySQL Port running inside container>
      - '5003:3306' # [NOTE] PROMJENI ZA SVAKI PROJEKAT PRVI BROJ
    expose: # Opens port 3306 on the container
      - '3306' # Where our data will be persisted
    volumes:
      - node-db:/home/daniel/Desktop/qStationProjekat # [NOTE] PROMJENI ZA SVAKI PROJEKAT
      - node-myql-logs:/home/daniel/Desktop/qStationProjekat/aaa # [NOTE] PROMJENI ZA SVAKI PROJEKAT

# Names our volume
volumes:
  node-db: # [NOTE] MORA BITI KAO GORE U VOLIUMSE IME
  node-myql-logs: # [NOTE] MORA BITI KAO GORE U VOLIUMSE IME